#!/bin/bash

# GitHub Discussions Auto-Setup Script
# Automatically configures GitHub Discussions for AI-powered feature suggestions

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "🎯 GitHub Discussions Auto-Setup"
echo ""
echo "This script will:"
echo "  1. Enable GitHub Discussions"
echo "  2. Create required labels"
echo "  3. Get Discussion category ID"
echo "  4. Update workflow configuration"
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}❌ GitHub CLI (gh) is not installed${NC}"
    echo ""
    echo "Install it with:"
    echo "  macOS:   brew install gh"
    echo "  Linux:   See https://github.com/cli/cli#installation"
    echo "  Windows: See https://github.com/cli/cli#installation"
    exit 1
fi

# Check if user is authenticated
if ! gh auth status &> /dev/null; then
    echo -e "${YELLOW}⚠️  Not authenticated with GitHub CLI${NC}"
    echo ""
    echo "Please run: gh auth login"
    exit 1
fi

# Get repository info
REPO_INFO=$(gh repo view --json owner,name 2>/dev/null || echo "")
if [ -z "$REPO_INFO" ]; then
    echo -e "${RED}❌ Not in a GitHub repository${NC}"
    echo "Please run this script from your repository directory"
    exit 1
fi

# Parse JSON manually (works without jq)
OWNER=$(echo "$REPO_INFO" | sed -n 's/.*"login":"\([^"]*\)".*/\1/p')
REPO=$(echo "$REPO_INFO" | sed -n 's/.*"name":"\([^"]*\)".*/\1/p')

if [ -z "$OWNER" ] || [ -z "$REPO" ]; then
    echo -e "${RED}❌ Failed to get repository information${NC}"
    echo "Debug info:"
    echo "$REPO_INFO"
    exit 1
fi

echo -e "${BLUE}📦 Repository: $OWNER/$REPO${NC}"
echo ""

# Step 1: Enable Discussions
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 1: Enabling GitHub Discussions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Check if discussions are already enabled
DISCUSSIONS_ENABLED=$(gh repo view --json hasDiscussionsEnabled -q '.hasDiscussionsEnabled')

if [ "$DISCUSSIONS_ENABLED" = "true" ]; then
    echo -e "${GREEN}✓${NC} Discussions already enabled"
else
    echo "Enabling Discussions..."

    # Enable discussions via API
    gh api \
        --method PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/$OWNER/$REPO" \
        -f has_discussions=true > /dev/null

    echo -e "${GREEN}✓${NC} Discussions enabled"

    # Wait a moment for GitHub to process
    sleep 2
fi

echo ""

# Step 2: Create required labels
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 2: Creating required labels"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Define labels to create (format: "name|color|description")
LABELS=(
    "approved|10b981|Approved feature suggestion ready for implementation"
    "rejected|ef4444|Feature suggestion rejected with explanation"
    "ai-generated|3b82f6|Automatically generated by AI"
    "needs-triage|fbbf24|Needs review and prioritization"
)

for label_info in "${LABELS[@]}"; do
    IFS='|' read -r label color description <<< "$label_info"

    # Try to create label, ignore if it already exists
    if gh label create "$label" --description "$description" --color "$color" 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Created label: $label"
    else
        # Check if it exists
        if gh label list | grep -q "^$label"; then
            echo -e "${YELLOW}ℹ${NC} Label already exists: $label"
        else
            echo -e "${RED}✗${NC} Failed to create label: $label"
        fi
    fi
done

echo ""

# Step 3: Get Discussion category ID
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 3: Getting Discussion category ID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Wait for discussions to be fully enabled
sleep 2

# Get discussion categories
CATEGORIES=$(gh api graphql -f query='
  query($owner: String!, $repo: String!) {
    repository(owner: $owner, name: $repo) {
      discussionCategories(first: 10) {
        nodes {
          id
          name
          description
        }
      }
    }
  }
' -f owner="$OWNER" -f repo="$REPO" 2>/dev/null || echo "")

if [ -z "$CATEGORIES" ]; then
    echo -e "${RED}✗${NC} Failed to fetch discussion categories"
    echo "Discussions may not be fully initialized yet. Please try again in a few moments."
    exit 1
fi

# Display available categories
echo "Available Discussion categories:"
echo "$CATEGORIES" | grep -o '"name":"[^"]*"' | cut -d'"' -f4 | while read -r name; do
    echo "  - $name"
done
echo ""

# Try to find "Ideas" or "General" category
CATEGORY_ID=$(echo "$CATEGORIES" | grep -B1 '"name":"Ideas"' | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$CATEGORY_ID" ]; then
    CATEGORY_ID=$(echo "$CATEGORIES" | grep -B1 '"name":"General"' | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
fi

if [ -z "$CATEGORY_ID" ]; then
    # Use the first category
    CATEGORY_ID=$(echo "$CATEGORIES" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
fi

if [ -z "$CATEGORY_ID" ]; then
    echo -e "${RED}✗${NC} Could not find any discussion category"
    exit 1
fi

CATEGORY_NAME=$(echo "$CATEGORIES" | grep -A1 "\"id\":\"$CATEGORY_ID\"" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)

echo -e "${GREEN}✓${NC} Using category: $CATEGORY_NAME"
echo -e "${BLUE}  Category ID: $CATEGORY_ID${NC}"
echo ""

# Step 4: Update workflow configuration
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 4: Updating workflow configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

WORKFLOW_FILE=".github/workflows/weekly-feature-suggestions.yml"

if [ ! -f "$WORKFLOW_FILE" ]; then
    echo -e "${YELLOW}⚠${NC} Workflow file not found: $WORKFLOW_FILE"
    echo "Skipping workflow update"
else
    # Check if category ID is already set
    CURRENT_ID=$(grep "categoryId:" "$WORKFLOW_FILE" | grep -o "DIC_[^'\"]*" || echo "")

    if [ "$CURRENT_ID" = "$CATEGORY_ID" ]; then
        echo -e "${GREEN}✓${NC} Category ID already configured correctly"
    else
        # Backup the file
        cp "$WORKFLOW_FILE" "$WORKFLOW_FILE.bak"

        # Update the category ID
        if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS
            sed -i '' "s/categoryId: '[^']*'/categoryId: '$CATEGORY_ID'/g" "$WORKFLOW_FILE"
            sed -i '' "s/categoryId: \"[^\"]*\"/categoryId: '$CATEGORY_ID'/g" "$WORKFLOW_FILE"
            sed -i '' "s/categoryId: DIC_[^ ]*/categoryId: '$CATEGORY_ID'/g" "$WORKFLOW_FILE"
        else
            # Linux
            sed -i "s/categoryId: '[^']*'/categoryId: '$CATEGORY_ID'/g" "$WORKFLOW_FILE"
            sed -i "s/categoryId: \"[^\"]*\"/categoryId: '$CATEGORY_ID'/g" "$WORKFLOW_FILE"
            sed -i "s/categoryId: DIC_[^ ]*/categoryId: '$CATEGORY_ID'/g" "$WORKFLOW_FILE"
        fi

        echo -e "${GREEN}✓${NC} Updated workflow with category ID"
        echo -e "${YELLOW}  (Backup saved: $WORKFLOW_FILE.bak)${NC}"
    fi
fi

echo ""

# Step 5: Verify setup
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 5: Verifying setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Check discussions
DISCUSSIONS_CHECK=$(gh repo view --json hasDiscussionsEnabled -q '.hasDiscussionsEnabled')
if [ "$DISCUSSIONS_CHECK" = "true" ]; then
    echo -e "${GREEN}✓${NC} Discussions: Enabled"
else
    echo -e "${RED}✗${NC} Discussions: Not enabled"
fi

# Check labels
REQUIRED_LABELS=("approved" "rejected" "ai-generated")
for label in "${REQUIRED_LABELS[@]}"; do
    if gh label list | grep -q "^$label"; then
        echo -e "${GREEN}✓${NC} Label: $label"
    else
        echo -e "${RED}✗${NC} Label: $label (missing)"
    fi
done

# Check workflow
if [ -f "$WORKFLOW_FILE" ]; then
    if grep -q "$CATEGORY_ID" "$WORKFLOW_FILE"; then
        echo -e "${GREEN}✓${NC} Workflow: Configured"
    else
        echo -e "${YELLOW}⚠${NC} Workflow: Category ID may not be set"
    fi
else
    echo -e "${YELLOW}⚠${NC} Workflow: File not found"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}✅ Setup complete!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show next steps
echo "📚 Next steps:"
echo ""
echo "1. ${GREEN}Commit the updated workflow file:${NC}"
echo "   git add .github/workflows/weekly-feature-suggestions.yml"
echo "   git commit -m 'chore: configure Discussion category ID'"
echo "   git push"
echo ""
echo "2. ${GREEN}Test the weekly feature suggestions workflow:${NC}"
echo "   - Go to Actions → Weekly Feature Suggestions → Run workflow"
echo "   - Check Discussions tab for the generated suggestions"
echo ""
echo "3. ${GREEN}Try the interactive commands:${NC}"
echo "   In a Discussion, comment:"
echo "   - @claude refine [your feedback]"
echo "   - @claude clarify [your question]"
echo "   - @claude analyze"
echo ""
echo "4. ${GREEN}Approve a suggestion:${NC}"
echo "   - Add the 'approved' label to a Discussion"
echo "   - Watch as Claude creates a spec and implementation PR!"
echo ""
echo "📖 Documentation:"
echo "   - Full guide: docs/feature-suggestion-workflow.md"
echo "   - README: Updated setup instructions"
echo ""
echo "🎉 Your AI-powered feature suggestion system is ready!"
echo ""
